/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project;

import com.project.dao.*;
import com.project.models.KhachHang;
import com.project.models.LichBay;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author johntoan98gmail.com
 */
public class JFrameLichBay extends javax.swing.JFrame {

    private LichBayDAO lichBayDAO = new LichBayDAO();
    private VeMayBayDAO veMayBayDAO = new VeMayBayDAO();

    /**
     * Creates new form KhachHang
     */
    public JFrameLichBay() {
        initComponents();
        loadLichBayTable();
    }

    private void loadLichBayTable() {
        try {
            List<LichBay> lichBays = lichBayDAO.findAll();
            DefaultTableModel model = (DefaultTableModel) jtb_Lich_Bay.getModel();
            model.setRowCount(0);  // Xóa các dòng cũ
            for (LichBay lb : lichBays) {
                model.addRow(new Object[]{lb.getLichBayID(), lb.getNoiDi(), lb.getNoiDen(), lb.getNgayGioBay(), lb.getGiaVe(), lb.getSoGhe()});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải danh sách lich bay: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_Lich_Bay = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtf_Noi_Di = new javax.swing.JTextField();
        jtf_Noi_Den = new javax.swing.JTextField();
        jtf_Thoi_Gian = new javax.swing.JTextField();
        jtf_So_Ghe = new javax.swing.JTextField();
        jtf_Gia_Ve = new javax.swing.JTextField();
        jbtn_Create = new javax.swing.JButton();
        jbtn_Edit = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jtf_Id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Danh Lịch Bay");

        jtb_Lich_Bay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nơi Đi", "Nơi Đến", "Thời Gian", "Giá Vé", "Số Ghế"
            }
        ));
        jtb_Lich_Bay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtb_Lich_BayFocusGained(evt);
            }
        });
        jtb_Lich_Bay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_Lich_BayMouseClicked(evt);
            }
        });
        jtb_Lich_Bay.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jtb_Lich_BayCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jtb_Lich_Bay);

        jLabel1.setText("Nơi Đi:");

        jLabel2.setText("Nơi Đến:");

        jLabel3.setText("Thời Gian:");

        jLabel4.setText("Giá Vé:");

        jLabel6.setText("Số Ghế:");

        jbtn_Create.setText("Thêm");
        jbtn_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_CreateActionPerformed(evt);
            }
        });

        jbtn_Edit.setText("Sửa");
        jbtn_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_EditActionPerformed(evt);
            }
        });

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Hủy");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setText("Id:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbtn_Create, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jbtn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)))
                                    .addComponent(jLabel7))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jtf_So_Ghe, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtf_Thoi_Gian, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_Noi_Den, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_Noi_Di, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jtf_Gia_Ve, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel5)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtf_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtf_Noi_Di, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtf_Noi_Den, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtf_Thoi_Gian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtf_So_Ghe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtf_Gia_Ve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_Create)
                    .addComponent(jbtn_Edit)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtb_Lich_BayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtb_Lich_BayFocusGained

    }//GEN-LAST:event_jtb_Lich_BayFocusGained

    private void jtb_Lich_BayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_Lich_BayMouseClicked
        int selectedRow = jtb_Lich_Bay.getSelectedRow();
        if (selectedRow != -1) {  // Kiểm tra xem có hàng nào được chọn
            String id = jtb_Lich_Bay.getValueAt(selectedRow, 0).toString();
            String email = jtb_Lich_Bay.getValueAt(selectedRow, 2).toString();
            String ten = jtb_Lich_Bay.getValueAt(selectedRow, 1).toString();
            String sdt = jtb_Lich_Bay.getValueAt(selectedRow, 3).toString();
            String diachi = jtb_Lich_Bay.getValueAt(selectedRow, 5).toString();
            String ngaysinh = jtb_Lich_Bay.getValueAt(selectedRow, 4).toString();
            jtf_So_Ghe.setText(diachi);
            jtf_Id.setText(id);
            jtf_Noi_Den.setText(email);
            jtf_Gia_Ve.setText(ngaysinh);
            jtf_Noi_Di.setText(ten);
            jtf_Thoi_Gian.setText(sdt);
        }
    }//GEN-LAST:event_jtb_Lich_BayMouseClicked

    private void jtb_Lich_BayCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jtb_Lich_BayCaretPositionChanged

    }//GEN-LAST:event_jtb_Lich_BayCaretPositionChanged

    private void jbtn_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_EditActionPerformed
          try {
        // Kiểm tra các trường không được để trống
        if (jtf_Id.getText().isEmpty() || jtf_Noi_Di.getText().isEmpty() || 
            jtf_Noi_Den.getText().isEmpty() || jtf_Thoi_Gian.getText().isEmpty() || 
            jtf_So_Ghe.getText().isEmpty() || jtf_Gia_Ve.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!");
            return;
        }

        // Lấy dữ liệu từ các trường nhập
        int lichBayID = Integer.parseInt(jtf_Id.getText());
        String maChuyenBay = jtf_Id.getText(); // Cần đổi lại tên biến cho đúng
        String noiDi = jtf_Noi_Di.getText();
        String noiDen = jtf_Noi_Den.getText();
        LocalDateTime ngayGioBay = LocalDateTime.parse(jtf_Thoi_Gian.getText());
        int soGhe = Integer.parseInt(jtf_So_Ghe.getText());
        BigDecimal giaVe = new BigDecimal(jtf_Gia_Ve.getText());

        // Kiểm tra ID tồn tại
        if (lichBayDAO.findById(lichBayID) == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy lịch bay với ID đã nhập!");
            return;
        }

        // Cập nhật thông tin lịch bay
        LichBay lichBay = new LichBay(lichBayID, maChuyenBay, noiDi, noiDen, ngayGioBay, soGhe, giaVe);
        lichBayDAO.update(lichBay);

        JOptionPane.showMessageDialog(this, "Cập nhật lịch bay thành công!");
        // Refresh lại bảng hoặc cập nhật danh sách nếu cần thiết
                loadLichBayTable();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Có lỗi xảy ra khi cập nhật lịch bay.");
    }
    }//GEN-LAST:event_jbtn_EditActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
       JFrameDatVe jFrameDatVe = new JFrameDatVe();
         jFrameDatVe.setLocationRelativeTo(null);
        jFrameDatVe.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
        int selectedRow = jtb_Lich_Bay.getSelectedRow();
        if (selectedRow != -1) {  // Kiểm tra xem có hàng nào được chọn
            int id = Integer.parseInt(jtb_Lich_Bay.getValueAt(selectedRow, 0).toString());

            // Hiển thị hộp thoại xác nhận
            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "Bạn có chắc chắn muốn xóa Lịch bay này?",
                    "Xác nhận xóa",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirm == JOptionPane.YES_OPTION) {
                // Thực hiện thao tác xóa nếu người dùng chọn "Yes"
                veMayBayDAO.deleteVeByLichBay(id);
                lichBayDAO.deleteById(id);
                JOptionPane.showMessageDialog(this, "Xóa Lịch bay thành công ");
                loadLichBayTable();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một Lịch bay để xóa.");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Có lỗi xảy ra khi xóa khách hàng.");
    }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jbtn_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_CreateActionPerformed
         try {
        // Kiểm tra các trường không được để trống
        if (jtf_Id.getText().isEmpty() || jtf_Noi_Di.getText().isEmpty() || 
            jtf_Noi_Den.getText().isEmpty() || jtf_Thoi_Gian.getText().isEmpty() || 
            jtf_So_Ghe.getText().isEmpty() || jtf_Gia_Ve.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!");
            return;
        }

        // Lấy dữ liệu từ các trường nhập
        int lichBayID = Integer.parseInt(jtf_Id.getText());
        String maChuyenBay = jtf_Id.getText(); // Cần đổi lại tên biến cho đúng
        String noiDi = jtf_Noi_Di.getText();
        String noiDen = jtf_Noi_Den.getText();
        LocalDateTime ngayGioBay = LocalDateTime.parse(jtf_Thoi_Gian.getText());  // Đảm bảo đúng định dạng
        int soGhe = Integer.parseInt(jtf_So_Ghe.getText());
        BigDecimal giaVe = new BigDecimal(jtf_Gia_Ve.getText());

        // Kiểm tra trùng ID
        if (lichBayDAO.findById(lichBayID) != null) {
            JOptionPane.showMessageDialog(this, "ID lịch bay đã tồn tại!");
            return;
        }

        // Tạo đối tượng lịch bay mới
        LichBay lichBay = new LichBay(lichBayID, maChuyenBay, noiDi, noiDen, ngayGioBay, soGhe, giaVe);

        // Thêm lịch bay vào cơ sở dữ liệu
        lichBayDAO.save(lichBay);

        JOptionPane.showMessageDialog(this, "Thêm lịch bay thành công!");
        // Refresh lại bảng hoặc cập nhật danh sách nếu cần thiết
                loadLichBayTable();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Có lỗi xảy ra khi thêm lịch bay.");
    }
    }//GEN-LAST:event_jbtn_CreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameLichBay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameLichBay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameLichBay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameLichBay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameLichBay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_Create;
    private javax.swing.JButton jbtn_Edit;
    private javax.swing.JTable jtb_Lich_Bay;
    private javax.swing.JTextField jtf_Gia_Ve;
    private javax.swing.JTextField jtf_Id;
    private javax.swing.JTextField jtf_Noi_Den;
    private javax.swing.JTextField jtf_Noi_Di;
    private javax.swing.JTextField jtf_So_Ghe;
    private javax.swing.JTextField jtf_Thoi_Gian;
    // End of variables declaration//GEN-END:variables
}
