/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project;

import com.project.dao.*;
import com.project.models.KhachHang;
import com.project.models.LichBay;
import com.project.models.VeMayBay;
import java.math.BigDecimal;
import java.sql.Date;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author johntoan98gmail.com
 */
public class JFrameDatVe extends javax.swing.JFrame {

    private KhachHangDAO khachHangDAO = new KhachHangDAO();
    private LichBayDAO lichBayDAO = new LichBayDAO();
    private VeMayBayDAO veMayBayDAO = new VeMayBayDAO();
    private double giaVe = 0;
    private int idKhach = 0, idLichBay = 0;

    /**
     * Creates new form DatVe
     */
    public JFrameDatVe() {
        initComponents();
        jtf_Ngay_Bay.setText(new Date(System.currentTimeMillis()).toString());
        loadKhachHangTable();
        loadLichBayTable();

    }

    private void loadKhachHangTable() {
        try {
            List<KhachHang> khachHangList = khachHangDAO.findAll();
            DefaultTableModel model = (DefaultTableModel) jtb_Khach_Hang.getModel();
            model.setRowCount(0);  // Xóa các dòng cũ
            for (KhachHang kh : khachHangList) {
                model.addRow(new Object[]{kh.getKhachHangID(), kh.getHoTen(), kh.getEmail(), kh.getSoDienThoai(), kh.getNgaySinh(), kh.getDiaChi()});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải danh sách khách hàng: " + e.getMessage());
        }
    }

    // Phương thức hiển thị danh sách lịch bay vào JTable
    private void loadLichBayTable() {
        try {
            List<LichBay> lichBayList = lichBayDAO.findAll();
            DefaultTableModel model = (DefaultTableModel) jtb_LichBay.getModel();
            model.setRowCount(0);  // Xóa các dòng cũ
            for (LichBay lb : lichBayList) {
                model.addRow(new Object[]{lb.getLichBayID(), lb.getNgayGioBay(), lb.getSoGhe(), lb.getGiaVe(), lb.getNoiDen(), lb.getNoiDi()});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải danh sách lịch bay: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_Khach_Hang = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtb_LichBay = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jtf_Ten_Khach = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbtn_Ten_Khach = new javax.swing.JButton();
        jbtn_Ngay_Bay = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtf_Ngay_Bay = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Danh sách khách hàng");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Danh sách lịch bay");

        jtb_Khach_Hang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Họ Tên", "Email", "Sdt", "Ngày Sinh", "Địa Chỉ"
            }
        ));
        jtb_Khach_Hang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtb_Khach_HangFocusGained(evt);
            }
        });
        jtb_Khach_Hang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_Khach_HangMouseClicked(evt);
            }
        });
        jtb_Khach_Hang.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jtb_Khach_HangCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jtb_Khach_Hang);

        jtb_LichBay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Ngày Bay", "Số Ghế", "Giá Vé", "Điểm Đến", "Điểm Đi"
            }
        ));
        jtb_LichBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_LichBayMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtb_LichBay);

        jLabel3.setText("Tên khách:");

        jLabel4.setText("Ngày bay:");

        jbtn_Ten_Khach.setText("Tìm");
        jbtn_Ten_Khach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_Ten_KhachActionPerformed(evt);
            }
        });

        jbtn_Ngay_Bay.setText("Tìm");
        jbtn_Ngay_Bay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_Ngay_BayActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 255));
        jButton3.setText("Đặt Vé");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Giao Diện Đặt Vé");

        jtf_Ngay_Bay.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        jtf_Ngay_Bay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_Ngay_BayActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Kiểm tra vé của khách");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("Danh Sách Khách Hàng");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 153, 153));
        jButton4.setText("Danh Sách Lịch Bay");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Đăng Xuất");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_Ten_Khach, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn_Ten_Khach)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_Ngay_Bay, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn_Ngay_Bay)))
                .addGap(122, 122, 122))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(211, 211, 211)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(480, 480, 480)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtf_Ten_Khach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn_Ten_Khach)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jbtn_Ngay_Bay)
                            .addComponent(jtf_Ngay_Bay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jButton3)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton2))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_Ten_KhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_Ten_KhachActionPerformed
        String tenKhach = jtf_Ten_Khach.getText();
        if (tenKhach.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên khách hàng.");
            return;
        }
        try {
            List<KhachHang> khachHangList = khachHangDAO.findByName(tenKhach);
            DefaultTableModel model = (DefaultTableModel) jtb_Khach_Hang.getModel();
            model.setRowCount(0);  // Xóa các dòng cũ
            for (KhachHang kh : khachHangList) {
                model.addRow(new Object[]{kh.getKhachHangID(),kh.getHoTen(), kh.getEmail(), kh.getSoDienThoai(), kh.getNgaySinh(), kh.getDiaChi()});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tìm kiếm khách hàng: " + e.getMessage());
        }
    }//GEN-LAST:event_jbtn_Ten_KhachActionPerformed

    private void jbtn_Ngay_BayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_Ngay_BayActionPerformed
        String ngayBayStr = jtf_Ngay_Bay.getText();
        if (ngayBayStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng định dạng ngày bay.");
            jtf_Ngay_Bay.setText(new Date(System.currentTimeMillis()).toString());

            return;
        }
        try {
            LocalDate ngayBay = LocalDate.parse(ngayBayStr, DateTimeFormatter.ofPattern("yyyy-MM-dd"));
            List<LichBay> lichBayList = lichBayDAO.findByDate(ngayBay);
            DefaultTableModel model = (DefaultTableModel) jtb_LichBay.getModel();
            model.setRowCount(0);  // Xóa các dòng cũ
            for (LichBay lb : lichBayList) {
                model.addRow(new Object[]{lb.getLichBayID(),lb.getNgayGioBay(), lb.getSoGhe(), lb.getGiaVe(), lb.getNoiDen(), lb.getNoiDi()});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tìm kiếm lịch bay: " + e.getMessage());
        }
    }//GEN-LAST:event_jbtn_Ngay_BayActionPerformed

    private void jtf_Ngay_BayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_Ngay_BayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_Ngay_BayActionPerformed

    private void jtb_Khach_HangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtb_Khach_HangFocusGained

    }//GEN-LAST:event_jtb_Khach_HangFocusGained

    private void jtb_Khach_HangCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jtb_Khach_HangCaretPositionChanged
    }//GEN-LAST:event_jtb_Khach_HangCaretPositionChanged

    private void jtb_Khach_HangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_Khach_HangMouseClicked
        int selectedRow = jtb_Khach_Hang.getSelectedRow();
        if (selectedRow != -1) {  // Kiểm tra xem có hàng nào được chọn
            String id = jtb_Khach_Hang.getValueAt(selectedRow, 0).toString();
            idKhach = Integer.parseInt(id);
        }
    }//GEN-LAST:event_jtb_Khach_HangMouseClicked

    private void jtb_LichBayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_LichBayMouseClicked
        int selectedRow = jtb_LichBay.getSelectedRow();
        if (selectedRow != -1) {  // Kiểm tra xem có hàng nào được chọn
            String id = jtb_LichBay.getValueAt(selectedRow, 0).toString();
            idLichBay = Integer.parseInt(id);
            giaVe = Double.parseDouble(jtb_LichBay.getValueAt(selectedRow, 3).toString());
        }
    }//GEN-LAST:event_jtb_LichBayMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (idKhach == 0 || idLichBay == 0) {
            JOptionPane.showMessageDialog(this, "Chưa chọn khách hàng hoặc lịch bay!");
            return;

        } else {
            VeMayBay veMayBay = new VeMayBay();
            veMayBay.setKhachHangID(idKhach);
            veMayBay.setLichBayID(idLichBay);
            veMayBay.setNgayDatVe(java.time.LocalDateTime.now());
            veMayBay.setTrangThai("done");
            veMayBay.setGiaVe(BigDecimal.valueOf(giaVe));
            veMayBayDAO.insertVe(veMayBay);
            JOptionPane.showMessageDialog(this, "Đặt vé thành công!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (idKhach == 0) {
            JOptionPane.showMessageDialog(this, "Chưa chọn khách hàng!");
            return;

        }
        this.setVisible(false);
        JFrameDanhSachVe jFrameDanhSachVe = new JFrameDanhSachVe(idKhach);
        jFrameDanhSachVe.setLocationRelativeTo(null);
        jFrameDanhSachVe.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        JFrameKhachHang jFrameKhachHang = new JFrameKhachHang();
        jFrameKhachHang.setLocationRelativeTo(null);
        jFrameKhachHang.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        JFrameLichBay jFrameLichBay = new JFrameLichBay();
        jFrameLichBay.setLocationRelativeTo(null);
        jFrameLichBay.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
        JFrameLogin jFrameDatVe = new JFrameLogin();
        jFrameDatVe.setLocationRelativeTo(null);
        jFrameDatVe.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameDatVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameDatVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameDatVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameDatVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameDatVe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtn_Ngay_Bay;
    private javax.swing.JButton jbtn_Ten_Khach;
    private javax.swing.JTable jtb_Khach_Hang;
    private javax.swing.JTable jtb_LichBay;
    private javax.swing.JFormattedTextField jtf_Ngay_Bay;
    private javax.swing.JTextField jtf_Ten_Khach;
    // End of variables declaration//GEN-END:variables
}
