/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project;

import com.project.dao.KhachHangDAO;
import com.project.dao.VeMayBayDAO;
import com.project.models.KhachHang;
import com.project.models.LichBay;
import com.project.models.VeMayBay;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author johntoan98gmail.com
 */
public class JFrameDanhSachVe extends javax.swing.JFrame {

    private VeMayBayDAO veMayBayDAO = new VeMayBayDAO();
    private KhachHangDAO khachHangDAO = new KhachHangDAO();
    private int idKhach;

    /**
     * Creates new form DanhSachVe
     */
    public JFrameDanhSachVe(int idKhach) {
        this.idKhach = idKhach;
        initComponents();
        veMayBayTable(idKhach);
    }
    // Phương thức hiển thị danh sách lịch bay vào JTable

    private void veMayBayTable(int idKhach) {
        try {
            KhachHang kh = khachHangDAO.findById(idKhach);
            jb_Ten.setText(kh.getHoTen());
            jl_Dia_Chi.setText(kh.getDiaChi());
            jl_sdt.setText(kh.getSoDienThoai());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        try {
            List<VeMayBay> lichBayList = veMayBayDAO.getAllVeMayBayByIdKhach(idKhach);
            DefaultTableModel model = (DefaultTableModel) jtb_LichBay.getModel();
            model.setRowCount(0);  // Xóa các dòng cũ
            for (VeMayBay lb : lichBayList) {
                model.addRow(new Object[]{lb.getVeID(), lb.getNgayDatVe(), lb.getLichBayID(), lb.getGiaVe(), lb.getTrangThai()});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải danh sách lịch bay: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jb_Ten = new javax.swing.JLabel();
        jl_sdt = new javax.swing.JLabel();
        jl_Dia_Chi = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtb_LichBay = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Danh Sách Vé");

        jLabel1.setText("Tên khách hàng:");

        jLabel2.setText("Số điện thoại :");

        jLabel3.setText("Địa chỉ:");

        jb_Ten.setForeground(new java.awt.Color(255, 153, 51));
        jb_Ten.setText("....");

        jl_sdt.setForeground(new java.awt.Color(255, 102, 51));
        jl_sdt.setText("...");

        jl_Dia_Chi.setForeground(new java.awt.Color(255, 102, 51));
        jl_Dia_Chi.setText("...");

        jtb_LichBay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Ngày Đặt Vé", "Lịch Bay Id", "Giá Vé", "Trạng Thái"
            }
        ));
        jtb_LichBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_LichBayMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtb_LichBay);

        jButton1.setText("Quay Lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Xóa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_Ten)
                            .addComponent(jl_Dia_Chi)
                            .addComponent(jl_sdt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jButton2)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jb_Ten))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jl_sdt, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jl_Dia_Chi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtb_LichBayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_LichBayMouseClicked
        int selectedRow = jtb_LichBay.getSelectedRow();
        if (selectedRow != -1) {  // Kiểm tra xem có hàng nào được chọn
            String id = jtb_LichBay.getValueAt(selectedRow, 0).toString();
//            idLichBay = Integer.parseInt(id);
//            giaVe = Double.parseDouble(jtb_LichBay.getValueAt(selectedRow, 3).toString());
        }
    }//GEN-LAST:event_jtb_LichBayMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
       JFrameDatVe jFrameDatVe = new JFrameDatVe();
         jFrameDatVe.setLocationRelativeTo(null);
        jFrameDatVe.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedRow = jtb_LichBay.getSelectedRow();
        if (selectedRow != -1) {  // Kiểm tra xem có hàng nào được chọn
            String id = jtb_LichBay.getValueAt(selectedRow, 0).toString();
            veMayBayDAO.deleteVe(Integer.parseInt(id));
            JOptionPane.showMessageDialog(this, "Xóa Thành Công");
            veMayBayTable(this.idKhach);
        }else{
            JOptionPane.showMessageDialog(this, "Chưa chọn vé");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameDanhSachVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameDanhSachVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameDanhSachVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameDanhSachVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameDanhSachVe(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jb_Ten;
    private javax.swing.JLabel jl_Dia_Chi;
    private javax.swing.JLabel jl_sdt;
    private javax.swing.JTable jtb_LichBay;
    // End of variables declaration//GEN-END:variables
}
